# Starship prompt configuration
# https://starship.rs/config/

command_timeout = 1000

[gcloud]
disabled = true

[memory_usage]
disabled = false
threshold = 0
format = "RAM: [$ram_pct]($style) | SWAP: [$swap_pct]($style) "
style = "bold yellow"