name: Setup Nix with Flakes
description: Installs Nix, enables flakes, and installs Home Manager

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Enable Flakes
      shell: bash
      run: |
        mkdir -p ~/.config/nix
        echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

    - name: Install Home Manager
      shell: bash
      run: |
        nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.05.tar.gz home-manager
        nix-channel --update
